<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BodyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BodyTypeRepository extends EntityRepository
{
}
