language: php
php:
    - '7.0'

before_script:
    - composer install
    - php bin/console assets:install --symlink

script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs src/ --standard=PSR2 --extensions=php
